# Delete instances for 3 tier application
- name: Instance Creation.
  os_server:
    #auth:
    #  auth_url: https://dynamic-labconsole.apps.shared.na.openshift.opentlc.com
    #  username: soumay.g-hcl.com
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    cloud: "{{ item.value.cloud }}"
  with_dict: "{{ osp_servers }}"

