# Delete Security Groups for different applications
- name: Delete Security Groups
  os_security_group: 
    cloud: "{{ item.value.cloud }}"
    name: "{{ item.value.security_group }}" 
    state: absent
  with_dict: "{{ osp_securitygroup }}"

