---
# vars file for osp.servers
osp_servers:
  frontend:
    name: frontend
    state: absent
    cloud: openstack
  
  app1:
    name: app1
    state: absent
    cloud: openstack
  app2:
    name: app2
    state: absent
    cloud: openstack
  db:
    name: db
    state: absent
    cloud: openstack

# Network Values
osp_networks:
  # Internal Network Details
  internal:
    cloud: openstack
    name: int_network

  # External Network Details
  external:
    cloud: openstack
    name: ext_network

# Subnet Values
osp_subnets:
  #Internal Subnet Details
  internal:
    cloud: openstack
    name: int_subnet
    
# External Subnet Details
  external:
    cloud: openstack
    name: ext_subnet

# Router Details
osp_router_cloud: openstack
osp_router_name: router

# Security Group & Rules
osp_securitygroup:
  #Rules for apps instances
  apps:
    security_group: apps
    cloud: openstack
  
  # Rules for frontend instance
  frontend:
    security_group: frontend
    cloud: openstack

  # Rules for db instances
  db:
    security_group: db
    cloud: openstack
remote_ip_prefix: 0.0.0.0/0

# Flavour Details
osp_flavour:
  cloud: openstack
  size: m1.medium
  ram: 2048
  vcpus: 1
  disk: 20

# Key Pair Details
