---
# vars file for osp.servers
osp_servers:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: frontend
    meta:
      - { group: frontends, deployment_name: QA}
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
  db:
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: db
    meta:
      - { group: appdbs, deployment_name: QA}

# Network Values
osp_networks:
  # Internal Network Details
  internal:
    cloud: openstack
    name: int_network
    external: false
    admin_state_up: yes
    provider_network_type: null
    provider_physical_network: null

  # External Network Details
  external:
    cloud: openstack
    name: ext_network
    external: true
    admin_state_up: false
    provider_network_type: flat
    provider_physical_network: datacenter

# Subnet Values
osp_subnets:
  #Internal Subnet Details
  internal:
    cloud: openstack
    name: int_subnet
    network_name: int_network
    cidr: 172.16.0.0/24
    ip_version: 4
    gateway_ip: null
    enable_dhcp: yes
    allocation_pool_start: null
    allocation_pool_end: null
    
# External Subnet Details
  external:
    cloud: openstack
    name: ext_subnet
    network_name: ext_network
    cidr: 192.0.2.0/24
    ip_version: 4
    gateway_ip: 192.0.2.254
    enable_dhcp: no
    allocation_pool_start: 192.0.2.150
    allocation_pool_end: 192.0.2.200


