---

# Internal Network Creation
- name: Create Internal & External Network
  os_network:
    cloud: "{{ item.value.cloud }}"
    state: present
    name: "{{ item.value.name }}"
    external: "{{ item.value.external }}"
    admin_state_up: "{{ item.value.admin_state_up }}" 
    provider_network_type: "{{ item.value.provider_network_type }}"
    provider_physical_network: "{{ item.value.provider_physical_network }}"
    wait: yes
  with_dict: "{{ osp_networks }}"

# Create Internal & External Subnet
- name: Create Internal & External Subnet
  os_subnet: 
    cloud: "{{ item.value.cloud }}"
    state: present
    name: "{{ item.value.name }}"
    network_name: "{{ item.value.network_name }}"
    cidr: "{{ item.value.cidr }}"
    ip_version: "{{ item.value.ip_version }}"
    gateway_ip: "{{ item.value.gateway_ip }}"
    enable_dhcp: "{{ item.value.enable_dhcp }}"
    allocation_pool_start: "{{ item.value.allocation_pool_start }}"
    allocation_pool_end: "{{ item.value.allocation_pool_end }}"
    wait: yes
    dns_nameservers: 
      - 8.8.8.8
  with_dict: "{{ osp_subnets }}"
